### PR TITLE
removing analytic derivative from AxAvtoExv (never used)

### LINKED ISSUE #80: Remove analytic derivative from AxAvToExv
If AxAvToExv only used in a compound model with other models, the analytic derivative code will never be used.  Probably better to remove it as it is not tested nor used.

### PR DESCRIPTION
**Pull request by karllark**
Closes #80.

### CODE REVIEW

**Comment by karllark** [comment]
This one is for you @pllim!

**Comment by pllim** [comment]
Nice! :100:

**Comment by karllark** [comment]
Did not manage 100%.  There is one line in the __init__.py file that is not tested that is to check the python version.  Not sure how to test this line.  See: https://coveralls.io/github/karllark/dust_extinction?branch=master

**Comment by sosey** [comment]
I think you can mock the sys.version return to be any python you want and test it that way

**Comment by sosey** [comment]
🙇‍♀ for 100% coverage dude

**Comment by karllark** [comment]
@sosey : can you point me to an example of such at test that does this mocking?  I'm just not sure how to do it.  Is this done by testing an import?  Definitely a learning opportunity for me.

**Comment by pllim** [comment]
Can't you just do a `# pragma: no cover` to exclude it from coverage math?

**Comment by karllark** [comment]
Yep, that will work.  Will do that for now until I can do a *real* test.  :-)

**Pull request merged**
