### PR TITLE
DEP: refactored out an undeclared runtime dependency on setuptools

### PR DESCRIPTION
**Pull request by neutrinoceros**
I noticed that this package had an undeclared runtime dependency on setuptools (which is where `pkg_resources` is found). I replaced it with standard lib API, following [this migration guide](https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename).

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Additional context: the reason this problem was never seen in CI is that `pytest-astropy` pulls in `setuptools` via `pytest-doctestplus`

**Comment by karllark** [comment]
This is great.  Thanks!  I've been aware of this issue, but just haven't found the time to fix it.  Awesome to get a PR with the fix!

**Comment by neutrinoceros** [comment]
@karllark I think the link check error is caused by upstream changes in how astropy’s developer docs is laid our (see https://github.com/astropy/astropy/pull/16561)

**Comment by karllark** [comment]
Yep.  I just fixed the link error by simplifying the readme.

How working to understand the new codecov upload to remove the rate limiter on the cov_test results.

**Comment by karllark** [comment]
Going to merge this PR as the failures are unrelated to the PR changes (e.g., all the tests passed).

**Pull request merged**
