### PR TITLE
dust_extinction_MODEL.evaluate() can take scalar input now

### PR DESCRIPTION
**Pull request by sohamvg**
resolving issue #108

### CODE REVIEW

**Comment by karllark** [comment]
This is great.   Thanks.  
Apologies for not merging yet, I'm trying to understand why the tests using single values did not catch this error previously.  For example, check out the last test in dust_extinction/tests/test_g16.py.  I will do some more investigation so that those tests can be updated.  Would be good to have the tests there so that this error does not sneak back in at some point in the future.

**Comment by karllark** [comment]
The difference might be due to calling the evaluate function explicitly.  In the tests, the model is defined, then called like:
`tmodel = CCM89(); 
result = tmodel(0.5*u.micron)`
instead of:
`result = CCM89.evaluate(0.5*u.micron)`
There may be some code in the astropy.modeling.Model class that handles the difference between a scaler and a vector.

**Comment by sohamvg** [comment]
I will also try to look into these tests and resolve the issues.

**Comment by karllark** [comment]
I'm going to merge this and then make tests to ensure that all the cases are caught and fixed.  Thanks for finding this bug and the solution.  Much appreciated.

**Pull request merged**
