### PR TITLE
Fix coverage reporting

### PR DESCRIPTION
**Pull request by saimn**
The job was running `pip install coveralls coveralls`, I think this change should fix it :crossed_fingers:

### CODE REVIEW

**Comment by saimn** [comment]
Yep, seems good: https://coveralls.io/jobs/63556225

**Comment by karllark** [comment]
Might have.  But travis is no longer reporting to the PR.  Argh.  Anyone, odd that it is stating 0.0% coverage.  Weird.

**Comment by karllark** [comment]
Having 0% reported when it should be 100% indicates to me that this issue is not fully solved.

**Comment by saimn** [comment]
Maybe because there is no real code change. coveralls says ` 0 of 0 relevant lines covered (NaN%)` :smile:

**Comment by karllark** [comment]
Moving to github actions and codecov.  PR #163.

**Pull request closed without merging**
